
name: NYC Yelow Taxi
description: Ingest NYC Taxi events.
steps:
    - name: Store
      activity: sdp_tpl_StoreAzureBlob
      variables:
        sdp_dir_root: '{sdp_dir_root}'
        sdp_blob_storage_container: '{sdp_blob_storage_container}'
      properties:
        PutAzureBlobStorage:
            storage-account-name: '{sdp_blob_storage_account}'
            storage-account-key: '{sdp_blob_storage_key}'
